from models import CPU, GPU, PSU, RAM, Storage, Motherboard
import random

# Sample CPU data
cpus = [
    CPU(
        maker= "Intel i9-13900KS",
        model= "13" ,
        performance= 86,
        price= 14499.00,
        power_consumption= 253,
        has_integrated_graphics= True,
        integrated_graphics_power= 17, #1
    ),
    CPU(
        maker= "Intel Core i9-13900K",
        model= "13",
        performance= 79,
        price= 11799.00,
        power_consumption= 253,
        has_integrated_graphics= True,
        integrated_graphics_power= 17,
    ),
    CPU(
        maker= "Intel Core i9-13900KF",
        model= "13",
        performance= 79,
        price= 10799.00,
        power_consumption= 253,
        has_integrated_graphics= False,
        integrated_graphics_power= 0,
    ),
    CPU(
        maker= "Intel Core i9-14900KF",
        model= "14",
        performance= 82,
        price= 10999.00,
        power_consumption= 253,
        has_integrated_graphics= False,
        integrated_graphics_power= 0,
    ),
    CPU(
        maker= "Intel Core i9-14900K",
        model= "14",
        performance= 82,
        price= 11099.00,
        power_consumption= 253,
        has_integrated_graphics= True,
        integrated_graphics_power= 17,
    ),
    CPU(
        maker= "Intel Core i9-14900F",
        model= "14",
        performance= 82,
        price= 10599.00,
        power_consumption= 219,
        has_integrated_graphics= False,
        integrated_graphics_power= 0,
    ),
    CPU(
        maker= "Intel Core i9-12900K",
        model= "12",
        performance= 69,
        price= 8999.00,
        power_consumption= 241,
        has_integrated_graphics= True,
        integrated_graphics_power= 17,
    ),
    CPU(
        maker= "Intel Core i9-12900KF",
        model= "12",
        performance= 69,
        price= 7999.00,
        power_consumption= 241,
        has_integrated_graphics= False,
        integrated_graphics_power= 0,
    ),
    CPU(
        maker= "Intel Core i9-11900K",
        model= "11",
        performance= 52,
        price= 8799.00,
        power_consumption= 125,
        has_integrated_graphics= True,
        integrated_graphics_power= 16,
    ),
    CPU(
        maker= "Intel Core i9-11900KF",
        model= "11",
        performance= 40,
        price= 6799.00,
        power_consumption= 125,
        has_integrated_graphics= False,
        integrated_graphics_power= 0,
    ),
    CPU(
        maker= "Intel Core i9-10900F",
        model= "10",
        performance= 34,
        price= 5599.00,
        power_consumption= 65,
        has_integrated_graphics= False,
        integrated_graphics_power= 0,
    ),
    CPU(
        maker= "Intel Core i9-10900K",
        model= "10",
        performance= 42,
        price= 9999.00,
        power_consumption= 125,
        has_integrated_graphics= True,
        integrated_graphics_power= 15,
    ),
    CPU(
        maker= "Intel Core i9-10900KF",
        model= "10",
        performance= 42,
        price= 8399.00,
        power_consumption= 95,
        has_integrated_graphics= False,
        integrated_graphics_power= 0,
    ),
    CPU(
        maker= "Intel Core i7-10700KA Edición Especial Marvel Avengers",
        model= "10",
        performance= 41,
        price= 8899.00,
        power_consumption= 125,
        has_integrated_graphics= True,
        integrated_graphics_power= 15,
    ),
    CPU(
        maker= "Intel Core i7-10700K",
        model= "10",
        performance= 41,
        price= 7199.00,
        power_consumption= 125,
        has_integrated_graphics= True,
        integrated_graphics_power= 16,
    ),
    CPU(
        maker= "Intel Core i7-10700F",
        model= "10",
        performance= 26,
        price= 3499.00,
        power_consumption= 65,
        has_integrated_graphics= True,
        integrated_graphics_power= 16,
    ),
    CPU(
        maker= "Intel Core i7-14700F",
        model= "14",
        performance= 54,
        price= 7299.00,
        power_consumption= 65,
        has_integrated_graphics= False,
        integrated_graphics_power= 0,
    ),
    CPU(
        maker= "Intel Core i7-14700",
        model= "14",
        performance= 54,
        price= 7699.00,
        power_consumption= 65,
        has_integrated_graphics= True,
        integrated_graphics_power= 15,
    ),
    CPU(
        maker= "Intel Core i7-14700K",
        model= "14",
        performance= 78,
        price= 8399.00,
        power_consumption= 253,
        has_integrated_graphics= True,
        integrated_graphics_power= 17,
    ),
    CPU(
        maker= "Intel Core i7-14700KF",
        model= "14",
        performance= 78,
        price= 7999.00,
        power_consumption= 253,
        has_integrated_graphics= False,
        integrated_graphics_power= 0,
    ),
    CPU(
        maker= "Intel Core i7-13700K",
        model= "13",
        performance= 73,
        price= 8199.00,
        power_consumption= 253,
        has_integrated_graphics= True,
        integrated_graphics_power= 17,
    ),
    CPU(
        maker= "Intel Core i7-13700",
        model= "13",
        performance= 59,
        price= 7599.00,
        power_consumption= 64,
        has_integrated_graphics= True,
        integrated_graphics_power= 17,
    ),
    CPU(
        maker= "Intel Core i7-12700",
        model= "12",
        performance= 39,
        price= 6499.00,
        power_consumption= 180,
        has_integrated_graphics= True,
        integrated_graphics_power= 15,
    ),
    CPU(
        maker= "Intel Core i7-12700K",
        model= "12",
        performance= 68,
        price= 6299.00,
        power_consumption= 190,
        has_integrated_graphics= True,
        integrated_graphics_power= 15,
    ),
    CPU(
        maker= "Intel Core i7-12700KF",
        model= "12",
        performance= 68,
        price= 6099.00,
        power_consumption= 190,
        has_integrated_graphics= False,
        integrated_graphics_power= 0,
    ),
    CPU(
        maker= "Intel Core i7-11700K",
        model= "11",
        performance= 35,
        price= 5199.00,
        power_consumption= 95,
        has_integrated_graphics= True,
        integrated_graphics_power= 11,
    ),
    CPU(
        maker= "Intel Core i7 11700KF",
        model= "11",
        performance= 35,
        price= 4799.00,
        power_consumption= 125,
        has_integrated_graphics= False,
        integrated_graphics_power= 0,
    ),
    CPU(
        maker= "Intel Core i7-11700F",
        model= "11",
        performance= 21,
        price= 3999.00,
        power_consumption= 65,
        has_integrated_graphics= False,
        integrated_graphics_power= 0,
    ),
    CPU(
        maker= "Intel Core i5-13600K",
        model= "13",
        performance= 70,
        price= 6299.00,
        power_consumption= 180,
        has_integrated_graphics= True,
        integrated_graphics_power= 16,
    ),
    CPU(
        maker= "Intel Core i5-13600KF",
        model= "13",
        performance= 70,
        price= 5799.00,
        power_consumption= 180,
        has_integrated_graphics= False,
        integrated_graphics_power= 0,
    ),
    CPU(
        maker= "Intel Core i5-13400",
        model= "13",
        performance= 42,
        price= 4599.00,
        power_consumption= 154,
        has_integrated_graphics= True,
        integrated_graphics_power= 16,
    ),
    CPU(
        maker= "Intel Core i5-14600K",
        model= "14",
        performance= 68,
        price= 6149.00,
        power_consumption= 180,
        has_integrated_graphics= True,
        integrated_graphics_power= 17,
    ),
    CPU(
        maker= "Intel Core i5-14400",
        model= "14",
        performance= 44,
        price= 4599.00,
        power_consumption= 148,
        has_integrated_graphics= True,
        integrated_graphics_power= 15,
    ),
    CPU(
        maker= "Intel Core i5-14600KF",
        model= "14",
        performance= 68,
        price= 5799.00,
        power_consumption= 180,
        has_integrated_graphics= False,
        integrated_graphics_power= 0,
    ),
    CPU(
        maker= "Intel Core i5-14400F",
        model= "14",
        performance= 44,
        price= 4199.00,
        power_consumption= 148,
        has_integrated_graphics= False,
        integrated_graphics_power= 0,
    ),
    CPU(
        maker= "Intel Core i5-12600K",
        model= "12",
        performance= 66,
        price= 5199.00,
        power_consumption= 150,
        has_integrated_graphics= True,
        integrated_graphics_power= 16,
    ),
    CPU(
        maker= "Intel Core i5-12400",
        model= "12",
        performance= 27,
        price= 3099.00,
        power_consumption= 117,
        has_integrated_graphics= True,
        integrated_graphics_power= 15,
    ),
    CPU(
        maker= "Intel Core i5-12400F",
        model= "12",
        performance= 27,
        price= 2899.00,
        power_consumption= 117,
        has_integrated_graphics= False,
        integrated_graphics_power= 0,
    ),
    CPU(
        maker= "Intel Core i5-12600KF",
        model= "12",
        performance= 66,
        price= 4599.00,
        power_consumption= 150,
        has_integrated_graphics= False,
        integrated_graphics_power= 0,
    ),
    CPU(
        maker= "Intel Core i5-10600KA Edición Especial Marvel Avengers",
        model= "10",
        performance= 41,
        price= 4899.00,
        power_consumption= 125,
        has_integrated_graphics= True,
        integrated_graphics_power= 16,
    ),
    CPU(
        maker= "Intel Core i5-10600K",
        model= "10",
        performance= 41,
        price= 4299.00,
        power_consumption= 125,
        has_integrated_graphics= True,
        integrated_graphics_power= 16,
    ),
    CPU(
        maker= "Intel Core i5-10400F",
        model= "10",
        performance= 24,
        price= 1999.00,
        power_consumption= 65,
        has_integrated_graphics= False,
        integrated_graphics_power= 0,
    ),
    CPU(
        maker= "Intel Core i5-10400",
        model= "10",
        performance= 24,
        price= 2499.00,
        power_consumption= 65,
        has_integrated_graphics= True,
        integrated_graphics_power= 16,
    ),
    CPU(
        maker= "Intel Core i5-11600KF",
        model= "11",
        performance= 40,
        price= 4699.00,
        power_consumption= 95,
        has_integrated_graphics= False,
        integrated_graphics_power= 0,
    ),
    CPU(
        maker= "Intel Core i5-11600K",
        model= "11",
        performance= 40,
        price= 6799.00,
        power_consumption= 125,
        has_integrated_graphics= True,
        integrated_graphics_power= 16,
    ),
    CPU(
        maker= "Intel Core i5-11400F",
        model= "11",
        performance= 23,
        price= 2299.00,
        power_consumption= 65,
        has_integrated_graphics= False,
        integrated_graphics_power= 0,
    ),
    CPU(
        maker= "Intel Core i5-11400",
        model= "11",
        performance= 23,
        price= 2399.00,
        power_consumption= 65,
        has_integrated_graphics= True,
        integrated_graphics_power= 15,
    ),
    CPU(
        maker= "Intel Core i5-9600K",
        model= "9",
        performance= 38,
        price= 4599.00,
        power_consumption= 95,
        has_integrated_graphics= True,
        integrated_graphics_power= 12,
    ),
    CPU(
        maker= "Procesador Intel Core i5 9400",
        model= "9",
        performance= 23,
        price= 3699.00,
        power_consumption= 65,
        has_integrated_graphics= True,
        integrated_graphics_power= 10,
    ),
    CPU(
        maker= "Intel Core i3-14100",
        model= "14",
        performance= 34,
        price= 2899.00,
        power_consumption= 100,
        has_integrated_graphics= True,
        integrated_graphics_power= 17,
    ),
    CPU(
        maker= "Intel Core i3-14100F",
        model= "14",
        performance= 34,
        price= 2599.00,
        power_consumption= 100,
        has_integrated_graphics= False,
        integrated_graphics_power= 0,
    ),
    CPU(
        maker= "Intel Core I3-13100",
        model= "13",
        performance= 31,
        price= 2899.00,
        power_consumption= 89,
        has_integrated_graphics= True,
        integrated_graphics_power= 16,
    ),
    CPU(
        maker= "Intel Core I3-13100F",
        model= "13",
        performance= 31,
        price= 2399.00,
        power_consumption= 89,
        has_integrated_graphics= False,
        integrated_graphics_power= 0,
    ),
    CPU(
        maker= "Intel Core i3-9100",
        model= "9",
        performance= 25,
        price= 2599.00,
        power_consumption= 65,
        has_integrated_graphics= True,
        integrated_graphics_power= 10,
    ),
    CPU(
        maker= "Intel Core i3-9100F",
        model= "9",
        performance= 25,
        price= 1999.00,
        power_consumption= 65,
        has_integrated_graphics= False,
        integrated_graphics_power= 0,
    ),
    CPU(
        maker= "Intel Core i3-12100",
        model= "12",
        performance= 30,
        price= 2299.00,
        power_consumption= 60,
        has_integrated_graphics= True,
        integrated_graphics_power= 12,
    ),
    CPU(
        maker= "Intel Core i3-12100F",
        model= "12",
        performance= 30,
        price= 1799.00,
        power_consumption= 60,
        has_integrated_graphics= False,
        integrated_graphics_power= 0,
    ),
    CPU(
        maker= "Intel Core i3-10105",
        model= "10",
        performance= 27,
        price= 1999.00,
        power_consumption= 65,
        has_integrated_graphics= True,
        integrated_graphics_power= 12,
    ),
    CPU(
        maker= "Intel Core i3-10105F",
        model= "10",
        performance= 27,
        price= 1399.00,
        power_consumption= 65,
        has_integrated_graphics= False,
        integrated_graphics_power= 0,
    ),
    CPU(
        maker= "Intel Core i3-10100",
        model= "10",
        performance= 20,
        price= 1899.00,
        power_consumption= 65,
        has_integrated_graphics= True,
        integrated_graphics_power= 16,
    ),
    CPU(
        maker= "Intel Core i3-10100F",
        model= "10",
        performance= 20,
        price= 1299.00,
        power_consumption= 65,
        has_integrated_graphics= False,
        integrated_graphics_power= 0,
    ),
    CPU(
        maker= "Intel Pentium Gold G7400",
        model= "G7",
        performance= 24,
        price= 1899.00,
        power_consumption= 46,
        has_integrated_graphics= True,
        integrated_graphics_power= 15,
    ),
    CPU(
        maker= "Intel Pentium Gold G6400",
        model= "G6",
        performance= 20,
        price= 1299.00,
        power_consumption= 58,
        has_integrated_graphics= True,
        integrated_graphics_power= 12,
    ),
    CPU(
        maker= "Intel Celeron G6900",
        model= "G6",
        performance= 15,
        price= 1199.00,
        power_consumption= 46,
        has_integrated_graphics= True,
        integrated_graphics_power= 15,
    ),
    CPU(
        maker= "Intel Celeron G5905",
        model= "G5",
        performance= 11,
        price= 959.00,
        power_consumption= 58,
        has_integrated_graphics= True,
        integrated_graphics_power= 7,
    ),
    CPU(
        maker= "AMD Ryzen 9 7900X",
        model= "7",
        performance= 56,
        price= 14999.00,
        power_consumption= 170,
        has_integrated_graphics= True,
        integrated_graphics_power= 22,
    ),
    CPU(
        maker= "AMD Ryzen 7 7700X",
        model= "7",
        performance= 50,
        price= 13999.00,
        power_consumption= 105,
        has_integrated_graphics= True,
        integrated_graphics_power= 22,
    ),
    CPU(
        maker= "AMD Ryzen 9 3900X",
        model= "3",
        performance= 43,
        price= 11499.00,
        power_consumption= 105,
        has_integrated_graphics= False,
        integrated_graphics_power= 0,
    ),
    CPU(
        maker= "AMD Ryzen 9 7950X3D",
        model= "7",
        performance= 59,
        price= 10799.00,
        power_consumption= 120,
        has_integrated_graphics= True,
        integrated_graphics_power= 16,
    ),
    CPU(
        maker= "AMD Ryzen 9 5950X",
        model= "5",
        performance= 46,
        price= 6999.00,
        power_consumption= 105,
        has_integrated_graphics= False,
        integrated_graphics_power= 0,
    ),
    CPU(
        maker= "AMD Ryzen 9 7900",
        model= "7",
        performance= 50,
        price= 6799.00,
        power_consumption= 65,
        has_integrated_graphics= True,
        integrated_graphics_power= 16,
    ),
    CPU(
        maker= "AMD Ryzen 9 5900X",
        model= "5",
        performance= 41,
        price= 5899.00,
        power_consumption= 105,
        has_integrated_graphics= False,
        integrated_graphics_power= 0,
    ),
    CPU(
        maker= "AMD Ryzen 7 3800X",
        model= "3",
        performance= 37,
        price= 8599.00,
        power_consumption= 105,
        has_integrated_graphics= False,
        integrated_graphics_power= 0,
    ),
    CPU(
        maker= "AMD Ryzen 7 8700G",
        model= "8",
        performance= 46,
        price= 6599.00,
        power_consumption= 65,
        has_integrated_graphics= True,
        integrated_graphics_power= 0,
    ),
    CPU(
        maker= "AMD Ryzen 7 5800X3D",
        model= "5",
        performance= 47,
        price= 6299.00,
        power_consumption= 105,
        has_integrated_graphics= False,
        integrated_graphics_power= 0,
    ),
    CPU(
        maker= "AMD Ryzen 7 7700X",
        model= "7",
        performance= 50,
        price= 5999.00,
        power_consumption= 105,
        has_integrated_graphics= True,
        integrated_graphics_power= 22,
    ),
    CPU(
        maker= "AMD Ryzen 7 7700",
        model= "7",
        performance= 46,
        price= 5699.00,
        power_consumption= 65,
        has_integrated_graphics= True,
        integrated_graphics_power= 16,
    ),
    CPU(
        maker= "AMD Ryzen 7 5700X 3D",
        model= "5",
        performance= 34,
        price= 4799.00,
        power_consumption= 105,
        has_integrated_graphics= False,
        integrated_graphics_power= 0,
    ),
    CPU(
        maker= "AMD Ryzen 7 5800X",
        model= "5",
        performance= 37,
        price= 4169.00,
        power_consumption= 105,
        has_integrated_graphics= False,
        integrated_graphics_power= 0,
    ),
    CPU(
        maker= "AMD Ryzen 7 5700",
        model= "5",
        performance= 35,
        price= 3099.00,
        power_consumption= 55,
        has_integrated_graphics= False,
        integrated_graphics_power= 0,
    ),
    CPU(
        maker= "AMD Ryzen 7 3700X",
        model= "3",
        performance= 41,
        price= 2999.00,
        power_consumption= 65,
        has_integrated_graphics= False,
        integrated_graphics_power= 0,
    ),
    CPU(
        maker= "AMD Ryzen 7 5700G APU",
        model= "5",
        performance= 40,
        price= 2849.00,
        power_consumption= 65,
        has_integrated_graphics= True,
        integrated_graphics_power= 16,
    ),
    CPU(
        maker= "AMD Ryzen 7 PRO 4750G",
        model= "4",
        performance= 22,
        price= 5999.00,
        power_consumption= 65,
        has_integrated_graphics= True,
        integrated_graphics_power= 13,
    ),
    CPU(
        maker= "AMD RYZEN 5 8600G",
        model="8",
        performance= 45,
        price= 4469.00,
        power_consumption= 65,
        has_integrated_graphics= True,
        integrated_graphics_power= 19,
    ),
    CPU(
        maker= "AMD RYZEN 5 3400G",
        model= "3",
        performance= 36,
        price= 4399.00,
        power_consumption= 65,
        has_integrated_graphics= True,
        integrated_graphics_power= 16,
    ),
    CPU(
        maker= "AMD Ryzen 5 7600X",
        model= "7",
        performance= 50,
        price= 4299.00,
        power_consumption= 105,
        has_integrated_graphics= True,
        integrated_graphics_power= 22,
    ),
    CPU(
        maker= "AMD Ryzen 5 7600",
        model= "7",
        performance= 45,
        price= 3799.00,
        power_consumption= 65,
        has_integrated_graphics= True,
        integrated_graphics_power= 16,
    ),
    CPU(
        maker= "AMD Ryzen 5 2600",
        model= "2",
        performance= 32,
        price= 3499.00,
        power_consumption= 65,
        has_integrated_graphics= False,
        integrated_graphics_power= 0,
    ),
    CPU(
        maker= "AMD RYZEN 5 2400G",
        model= "2",
        performance= 35,
        price= 3199.00,
        power_consumption= 65,
        has_integrated_graphics= True,
        integrated_graphics_power= 18,
    ),
    CPU(
        maker= "AMD Ryzen 5 5600X",
        model= "5",
        performance= 41,
        price= 2899.00,
        power_consumption= 65,
        has_integrated_graphics= False,
        integrated_graphics_power= 0,
    ),
    CPU(
        maker= "AMD RYZEN 5 5600GT",
        model= "5",
        performance= 39,
        price= 2749.00,
        power_consumption= 45,
        has_integrated_graphics= True,
        integrated_graphics_power= 16,
    ),
    CPU(
        maker= "AMD Ryzen 5 5600",
        model= 5,
        performance= 41,
        price= 2599.00,
        power_consumption= 45,
        has_integrated_graphics= False,
        integrated_graphics_power= 0,
    ),
    CPU(
        maker= "AMD Ryzen 5 3600",
        model= "3",
        performance= 40,
        price= 2499.00,
        power_consumption= 65,
        has_integrated_graphics= False,
        integrated_graphics_power= 0,
    ),
    CPU(
        maker= "AMD Ryzen 5 PRO 4650G",
        model= "4",
        performance= 21,
        price= 2099.00,
        power_consumption= 65,
        has_integrated_graphics= True,
        integrated_graphics_power= 15,
    ),
    CPU(
        maker= "AMD Ryzen 5 5500",
        model= "5",
        performance= 38,
        price= 1799.00,
        power_consumption= 65,
        has_integrated_graphics= False,
        integrated_graphics_power= 0,
    ),
    CPU(
        maker= "AMD Ryzen 5 3600X",
        model= "3",
        performance= 42,
        price= 1599.00,
        power_consumption= 95,
        has_integrated_graphics= False,
        integrated_graphics_power= 0,
    ),
    CPU(
        maker= "AMD RYZEN 5 5600G",
        model= "5",
        performance= 44,
        price= 2399.00,
        power_consumption= 65,
        has_integrated_graphics= True,
        integrated_graphics_power= 10,
    ),
    CPU(
        maker= "AMD Ryzen 5 4500",
        model= "4",
        performance= 37,
        price= 1299.00,
        power_consumption= 65,
        has_integrated_graphics= False,
        integrated_graphics_power= 0,
    ),
    CPU(
        maker= "AMD Ryzen 3 PRO 4350G",
        model= "4",
        performance= 19,
        price= 3599.00,
        power_consumption= 65,
        has_integrated_graphics= True,
        integrated_graphics_power= 16,
    ),
    CPU(
        maker= "AMD Ryzen 3 3300X",
        model= "3",
        performance= 33,
        price= 2999.00,
        power_consumption= 65,
        has_integrated_graphics= False,
        integrated_graphics_power= 0,
    ),
    CPU(
        maker= "AMD RYZEN 3 2200G APU",
        model= "2",
        performance= 31,
        price= 2299.00,
        power_consumption= 65,
        has_integrated_graphics= True,
        integrated_graphics_power= 17,
    ),
    CPU(
        maker= "AMD RYZEN 3 3200G APU",
        model= "3",
        performance= 35,
        price= 1299.00,
        power_consumption= 65,
        has_integrated_graphics= True,
        integrated_graphics_power= 17,
    ),
    CPU(
        maker= "AMD Athlon 240GE",
        model= "T2",
        performance= 12,
        price= 1759.00,
        power_consumption= 35,
        has_integrated_graphics= True,
        integrated_graphics_power= 13,
    ),
    CPU(
        maker= "AMD A8 9600",
        model= "A8",
        performance= 31,
        price= 1379.00,
        power_consumption= 35,
        has_integrated_graphics= True,
        integrated_graphics_power= 10,
    ),
    CPU(
        maker= "AMD A6 9500",
        model= "A6",
        performance= 20,
        price= 1179.00,
        power_consumption= 65,
        has_integrated_graphics= True,
        integrated_graphics_power= 7,
    ),
    CPU(
        maker= "AMD Athlon 3000G",
        model= "T3",
        performance= 19,
        price= 849.00,
        power_consumption= 35,
        has_integrated_graphics= True,
        integrated_graphics_power= 9,
    ),
]

"""
----------------------------------------------------------------------------------
"""

gpus = [
    None,
    
    GPU(
        maker= "NVIDIA GeForce GT 710",
        price= 849.00,
        power_consumption= 19,
        power= 19
    ),
    GPU(
        maker= "NVIDIA GeForce MSI GT 1030",
        price= 1599.00,
        power_consumption= 20,
        power= 14
    ),
    GPU(
        maker= "MSI NVIDIA GeForce GTX 1650",
        price= 2799.00,
        power_consumption= 75,
        power= 21
    ),
    GPU(
        maker= "Sapphire Pulse AMD Radeon RX 6400",
        price= 2949.00,
        power_consumption= 350,
        power= 28
    ),
    GPU(
        maker= "Gigabyte NVIDIA GeForce GTX 1650 OC",
        price= 2999.00,
        power_consumption= 300,
        power= 23
    ),
    GPU(
        maker= "Gigabyte AMD Radeon RX 6400 EAGLE",
        price= 2999.00,
        power_consumption= 350,
        power= 39
    ),
    GPU(
        maker= "AMD Radeon RX 6500 XT",
        price= 2999.00,
        power_consumption= 400,
        power= 36
    ),
    GPU(
        maker= "GIGABYTE RTX 3050 OC",
        price= 3999.00,
        power_consumption= 300,
        power= 31
    ),
    GPU(
        maker= "Radeon RX 6600 8GB",
        price= 3999.00,
        power_consumption= 350,
        power= 45
    ),
    GPU(
        maker= "NVIDIA GeForce RTX 3050",
        price= 4399.00,
        power_consumption= 500,
        power= 37
    ),
    GPU(
        maker= "NVIDIA GeForce GTX 1650",
        price= 4599.00,
        power_consumption= 300,
        power= 21
    ),
    GPU(
        maker= "ZOTAC GAMING GeForce RTX 3060",
        price= 4999.00,
        power_consumption= 600,
        power= 39
    ),
    GPU(
        maker= "Intel ARC A770 Phantom",
        price= 4999.00,
        power_consumption= 700,
        power= 52
    ),
    GPU(
        maker= "Speedster QICK 308 Radeon RX 7600",
        price= 5299.00,
        power_consumption= 550,
        power= 52
    ),
    GPU(
        maker= "PNY NVIDIA GeForce RTX 4060",
        price= 5799.00,
        power_consumption= 550,
        power= 52
    ),
    GPU(
        maker= "Radeon RX 6500 XT 4GB GDDR6",
        price= 6299.00,
        power_consumption= 500,
        power= 46
    ),
    GPU(
        maker= "XFX Speedster QICK319 Radeon RX 6750XT",
        price= 6599.00,
        power_consumption= 650,
        power= 54
    ),
    GPU(
        maker= "Radeon XFX RX 7600XT",
        price= 6799.00,
        power_consumption= 550,
        power= 52
    ),
    GPU(
        maker= "Nvidia Geforce RTX 2060",
        price= 7699.00,
        power_consumption= 500,
        power= 36
    ),
    GPU(
        maker= "Radeon RX 7700 XT",
        price= 8799.00,
        power_consumption= 560,
        power= 60
    ),
    GPU(
        maker= "Radeon RX 6800",
        price= 9699.00,
        power_consumption= 650,
        power= 61
    ),
    GPU(
        maker= "RTX 3070 Ti Asus Tuf OC Edition 8 Gb",
        price= 9999.00,
        power_consumption= 750,
        power= 61
    ),
    GPU(
        maker= "Radeon PULSE RX 7800 XT",
        price= 9999.00,
        power_consumption= 700,
        power= 58
    ),
    GPU(
        maker= "Zotac NVIDIA GeForce RTX 4070 Twin Edge OC",
        price= 10699.00,
        power_consumption= 600,
        power= 58
    ),
    GPU(
        maker= "SAPPHIRE NITRO RX 7900 GRE 16GB OC",
        price= 11699.00,
        power_consumption= 750,
        power= 85
    ),
    GPU(
        maker= "I NVIDIA GeForce RTX 4070 VENTUS 2X WHITE 12G OC",
        price= 11299.00,
        power_consumption= 650,
        power= 66
    ),
    GPU(
        maker= "TX 4080 Super Ventus 3X OC",
        price= 19999.00,
        power_consumption= 750,
        power= 71
    ),
    GPU(
        maker= "GeForce RTX 4090",
        price= 34999.00,
        power_consumption= 850,
        power= 94
    ),
    GPU(
        maker= "NVIDIA GeForce RTX 4090 AERO OC 24G",
        price= 39999.00,
        power_consumption= 1000,
        power= 100
    ),
]


"""
----------------------------------------------------------------------------------
"""

# Sample RAM data
rams = [
    RAM(
        maker="G.Skill",
        model="Trident Z5 RGB",
        capacity=32,
        frequency=6000,
        type="DDR5",
        price=2999.99,
    ),
    RAM(
        maker="Corsair",
        model="Dominator Platinum RGB",
        capacity=8,
        frequency=5600,
        type="DDR5",
        price=1999.99,
    ),
    RAM(
        maker="Crucial",
        model="Ballistix MAX",
        capacity=64,
        frequency=4800,
        type="DDR5",
        price=3049.99,
    ),
    RAM(
        maker="Kingston",
        model="FURY Renegade",
        capacity=32,
        frequency=5200,
        type="DDR4",
        price=3449.99,
    ),
    RAM(
        maker="Team Group",
        model="T-Force Delta RGB",
        capacity=16,
        frequency=6000,
        type="DDR5",
        price=1579.99,
    ),
    RAM(
        maker="G.Skill",
        model="Trident Z Royal",
        capacity=8,
        frequency=4000,
        type="DDR4",
        price=749.99,
    ),
    RAM(
        maker="Corsair",
        model="Vengeance RGB Pro",
        capacity=16,
        frequency=3600,
        type="DDR4",
        price=1099.99,
    ),
    RAM(
        maker="Crucial",
        model="Ballistix",
        capacity=8,
        frequency=3200,
        type="DDR4",
        price=949.99,
    ),
    RAM(
        maker="Kingston",
        model="FURY Beast",
        capacity=16,
        frequency=3600,
        type="DDR4",
        price=1289.99,
    ),
    RAM(
        maker="Team Group",
        model="T-Force Vulcan Z",
        capacity=32,
        frequency=3600,
        type="DDR4",
        price=2779.99,
    ),
        RAM(
        maker="Adata",
        model="XPG Gammix D10",
        capacity=8,
        frequency=3200,
        type="DDR4",
        price=399.00,
    ),
    RAM(
        maker="Adata",
        model="XPG Gammix D45 1x16GB Negra",
        capacity=16,
        frequency=3600,
        type="DDR4",
        price=729.00,
    ),
    RAM(
        maker="Kingston",
        model="FURY Renegade RGB",
        capacity=32,
        frequency=3600,
        type="DDR4",
        price=1549.00,
    ),
    RAM(
        maker="Corsair",
        model="Vengeance",
        capacity=64,
        frequency=5200,
        type="DDR4",
        price=2899.00,
    ),
    RAM(
        maker="Kingston",
        model="Fury Beast Black",
        capacity=8,
        frequency=6000,
        type="DDR5",
        price=670.86,
    ),
    RAM(
        maker="Kingston",
        model="FURY Renegade White RGB",
        capacity=16,
        frequency=6000,
        type="DDR5",
        price=1549.00,
    ),
    RAM(
        maker="Kingston",
        model="FURY Beast RGB",
        capacity=32,
        frequency=6000,
        type="DDR5",
        price=2549.00,
    ),
    RAM(
        maker="XPG",
        model="Lancer Blade RGB",
        capacity=48,
        frequency=6000,
        type="DDR5",
        price=3500.00,
    ),
    
    RAM(
        maker="Crucial",
        model="Ballistix Sport LT",
        capacity=8,
        frequency=2666,
        type="DDR4",
        price=480.99,
    ),
    RAM(
        maker="Corsair",
        model="Vengeance LPX",
        capacity=8,
        frequency=3000,
        type="DDR4",
        price=620.99,
    ),
    RAM(
        maker="G.Skill",
        model="Ripjaws V Series",
        capacity=16,
        frequency=3200,
        type="DDR4",
        price=710.99,
    ),
    RAM(
        maker="Crucial",
        model="Ballistix Elite",
        capacity=32,
        frequency=3600,
        type="DDR4",
        price=900.99,
    ),
    RAM(
        maker="Corsair",
        model="Vengeance RGB Pro",
        capacity=64,
        frequency=4000,
        type="DDR4",
        price=1899.99,
    ),
    RAM(
        maker="G.Skill",
        model="Trident Z Royal",
        capacity=128,
        frequency=4800,
        type="DDR4",
        price=8999.99,
    ),
    RAM(
        maker="Crucial",
        model="Ballistix DDR5",
        capacity=16,
        frequency=4800,
        type="DDR5",
        price=899.99,
    ),
    RAM(
        maker="Corsair",
        model="Vengeance LPX DDR5",
        capacity=32,
        frequency=5600,
        type="DDR5",
        price=1099.99,
    ),
    RAM(
        maker="G.Skill",
        model="Trident Z DDR5",
        capacity=64,
        frequency=6400,
        type="DDR5",
        price=2299.99,
    ),
    RAM(
        maker="Kingston",
        model="FURY Beast DDR5",
        capacity=128,
        frequency=8000,
        type="DDR5",
        price=11999.99,
    ),

]

"""
----------------------------------------------------------------------------------
"""

# Sample Storage data
storages =  [
    Storage(
        maker="Samsung",
        model="970 EVO Plus",
        type="SSD",
        capacity=2000.0,
        price=4999.99,
    ),
    Storage(
        maker="Crucial",
        model="MX500",
        type="SSD",
        capacity=1000.0,
        price=3999.99,
    ),
    Storage(
        maker="Western Digital",
        model="Black",
        type="HDD",
        capacity=6000.0,
        price=1649.99,
    ),
    Storage(
        maker="Kingston",
        model="KC3000",
        type="SSD",
        capacity=4000.0,
        price=6_099.99,
    ),
    Storage(
        maker="Sabrent",
        model="Rocket 4 Plus",
        type="SSD",
        capacity=2000.0,
        price=2_049.99,
    ),
    Storage(
        maker="Sandisk",
        model="Ultra 3D",
        type="SSD",
        capacity=1000.0,
        price=2_879.99,
    ),
    Storage(
        maker="Intel",
        model="670p",
        type="SSD",
        capacity=2000.0,
        price=899.99,
    ),
    Storage(
        maker="Gigabyte",
        model="2280",
        type="SSD",
        capacity=128.0,
        price=689.99,
    ),
    Storage(
        maker="HP",
        model="S650",
        type="SSD",
        capacity=2000.0,
        price=399.99,
    ),
    Storage(
        maker="Gigabyte",
        model="M.2 NVMe 2280",
        type="SSD",
        capacity=128,
        price=299.00,
    ),
    Storage(
        maker="HP",
        model="S650",
        type="SSD",
        capacity=240,
        price=399.00,
    ),
    Storage(
        maker="Kingston",
        model="A400",
        type="SSD",
        capacity=480,
        price=549.00,
    ),
    Storage(
        maker="Adata",
        model="XPG Spectrix",
        type="SSD",
        capacity=512,
        price=649.00,
    ),
    Storage(
        maker="Adata",
        model="SU630",
        type="SSD",
        capacity=960,
        price=999.00,
    ),
    Storage(
        maker="Western Digital",
        model="WD Green",
        type="SSD",
        capacity=2000,
        price=1799.00,
    ),
    Storage(
        maker="Adata",
        model="Ultimate SU630",
        type="SSD",
        capacity=2500,
        price=1999.00,
    ),
    Storage(
        maker="Acer",
        model="GM7 NVMe",
        type="SSD",
        capacity=4000,
        price=3799.00,
    ),
    
        Storage(
        maker="Samsung",
        model="970 EVO",
        type="SSD",
        capacity=500,
        price=5699,
    ),
    Storage(
        maker="Crucial",
        model="MX500",
        type="SSD",
        capacity=1000,
        price=139.99,
    ),
    Storage(
        maker="SanDisk",
        model="Ultra 3D",
        type="SSD",
        capacity=2000,
        price=3172.06,
    ),
    Storage(
        maker="Western Digital",
        model="Blue SN550",
        type="SSD",
        capacity=500,
        price=839,
    ),
    Storage(
        maker="Seagate",
        model="FireCuda 520",
        type="SSD",
        capacity=2000,
        price=5850.00,
    ),
    Storage(
        maker="ADATA",
        model="XPG GAMMIX S70",
        type="SSD",
        capacity=2000,
        price=2557.99,
    ),
        Storage(
        maker="Intel",
        model="Optane M10",
        type="SSD",
        capacity=16,
        price=70.00,
    ),
    
  
]



"""
----------------------------------------------------------------------------------
"""



motherboards = [
    Motherboard(
        maker="Asus",
        model="ROG Maximus Z790",
        price=10599.00,
        power_consumption=30,
        max_ram_capacity=128,
        max_ram_frequency=8000,
        ram_socket_type="DDR5",
        compatible_cpus=[14, 13, 12, "G7"],
    ),
    Motherboard(
        maker="ASRock",
        model="Z690",
        price=9199.00,
        power_consumption=30,
        max_ram_capacity=128,
        max_ram_frequency=8000,
        ram_socket_type="DDR5",
        compatible_cpus=[14, 13, 12, "G7"],
    ),
    Motherboard(
        maker="Gigabyte",
        model="Z790 AORUS PRO",
        price=6999.00,
        power_consumption=32,
        max_ram_capacity=128,
        max_ram_frequency=8000,
        ram_socket_type="DDR5",
        compatible_cpus=[14, 13, 12, "G7"],
    ),
    Motherboard(
        maker="Gigabyte",
        model="Z690 AERO",
        price=6599.00,
        power_consumption=30,
        max_ram_capacity=128,
        max_ram_frequency=5200,
        ram_socket_type="DDR4",
        compatible_cpus=[14, 13, 12, "G7"],
    ),
    Motherboard(
        maker="Gigabyte",
        model="B650I AORUS Ultra",
        price=6299.00,
        power_consumption=25,
        max_ram_capacity=96,
        max_ram_frequency=6400,
        ram_socket_type="DDR5",
        compatible_cpus=[7, 8],
    ),
    Motherboard(
        maker="NZXT",
        model="N7 B650E",
        price=6149.00,
        power_consumption=28,
        max_ram_capacity=128,
        max_ram_frequency=8000,
        ram_socket_type="DDR5",
        compatible_cpus=[7, 8],
    ),
    Motherboard(
        maker="ASUS",
        model="ATX Prime X670E",
        price=5799.00,
        power_consumption=25,
        max_ram_capacity=128,
        max_ram_frequency=8000,
        ram_socket_type="DDR5",
        compatible_cpus=[7, 8],
    ),
    Motherboard(
        maker="Gigabyte",
        model="Z790 UD",
        price=4199.00,
        power_consumption=25,
        max_ram_capacity=196,
        max_ram_frequency=8000,
        ram_socket_type="DDR5",
        compatible_cpus=[14, 13, 12, "G7"],
    ),
    Motherboard(
        maker="Aorus",
        model="Elite AX",
        price=4199.00,
        power_consumption=23,
        max_ram_capacity=128,
        max_ram_frequency=8000,
        ram_socket_type="DDR5",
        compatible_cpus=[7, 8],
    ),
    Motherboard(
        maker="Gigabyte",
        model="B760M Aorus Elite",
        price=3799.00,
        power_consumption=35,
        max_ram_capacity=192,
        max_ram_frequency=8000,
        ram_socket_type="DDR5",
        compatible_cpus=[14, 13, 12, "G7"],
    ),
    Motherboard(
        maker="MSI",
        model="B760M Project Zero",
        price=3699.00,
        power_consumption=32,
        max_ram_capacity=256,
        max_ram_frequency=8000,
        ram_socket_type="DDR5",
        compatible_cpus=[14, 13, 12, "G7"],
    ),
    Motherboard(
        maker="Asus",
        model="ROG STRIX B550",
        price=3699.00,
        power_consumption=27,
        max_ram_capacity=128,
        max_ram_frequency=5200,
        ram_socket_type="DDR4",
        compatible_cpus=["5", "4", "3", "2", "T2", "A8", "A6", "T3"],
    ),
    Motherboard(
        maker="MSI",
        model="MAG B550",
        price=3499.00,
        power_consumption=27,
        max_ram_capacity=128,
        max_ram_frequency=5200,
        ram_socket_type="DDR4",
        compatible_cpus=["5", "4", "3", "2", "T2", "A8", "A6", "T3"],
    ),
    Motherboard(
        maker="ASUS",
        model="Micro ATX PRIME B650M-A AX II",
        price=3499.00,
        power_consumption=25,
        max_ram_capacity=128,
        max_ram_frequency=8000,
        ram_socket_type="DDR5",
        compatible_cpus=[7, 8],
    ),
    Motherboard(
        maker="MSI",
        model="Atx MAG B760 TOMAHAWK",
        price=3499.00,
        power_consumption=23,
        max_ram_capacity=128,
        max_ram_frequency=5200,
        ram_socket_type="DDR4",
        compatible_cpus=[14, 13, 12, "G7"],
    ),
    Motherboard(
        maker="ASRock",
        model="H670 Steel Legend",
        price=2999.00,
        power_consumption=25,
        max_ram_capacity=128,
        max_ram_frequency=5200,
        ram_socket_type="DDR4",
        compatible_cpus=[14, 13, 12, "G7"],
    ),
    Motherboard(
        maker="Asrock",
        model="B550 EXTREME4",
        price=2849.00,
        power_consumption=20,
        max_ram_capacity=64,
        max_ram_frequency=5000,
        ram_socket_type="DDR4",
        compatible_cpus=["5", "4", "3", "2", "T2", "A8", "A6", "T3"],
    ),
    Motherboard(
        maker="Gigabyte",
        model="A620M GAMING X",
        price=2499.00,
        power_consumption=25,
        max_ram_capacity=192,
        max_ram_frequency=8000,
        ram_socket_type="DDR5",
        compatible_cpus=[7, 8],
    ),
    Motherboard(
        maker="Gigabyte",
        model="B760M Gaming",
        price=2499.00,
        power_consumption=26,
        max_ram_capacity=96,
        max_ram_frequency=8000,
        ram_socket_type="DDR5",
        compatible_cpus=[14, 13, 12, "G7"],
    ),
    Motherboard(
        maker="Gigabyte",
        model="B760M DS3H",
        price=2499.00,
        power_consumption=23,
        max_ram_capacity=128,
        max_ram_frequency=5000,
        ram_socket_type="DDR4",
        compatible_cpus=[14, 13, 12, "G7"],
    ),
    Motherboard(
        maker="Gigabyte",
        model="Mini-ITX A520I AC",
        price=2299.00,
        power_consumption=15,
        max_ram_capacity=64,
        max_ram_frequency=5200,
        ram_socket_type="DDR4",
        compatible_cpus=["5", "4", "3", "2", "T2", "A8", "A6", "T3"],
    ),
    Motherboard(
        maker="ASUS",
        model="H610M-K",
        price=1949.00,
        power_consumption=15,
        max_ram_capacity=96,
        max_ram_frequency=8000,
        ram_socket_type="DDR5",
        compatible_cpus=[14, 13, 12, "G7"],
    ),
    Motherboard(
        maker="Micro ATX",
        model="B550M",
        price=1999.00,
        power_consumption=18,
        max_ram_capacity=128,
        max_ram_frequency=8000,
        ram_socket_type="DDR4",
        compatible_cpus=["5", "4", "3", "2", "T2", "A8", "A6", "T3"],
    ),
    Motherboard(
        maker="Micro-ATX",
        model="PRIME A620M-K",
        price=1899.00,
        power_consumption=23,
        max_ram_capacity=96,
        max_ram_frequency=8000,
        ram_socket_type="DDR5",
        compatible_cpus=[7, 8],
    ),
    Motherboard(
        maker="Gigabyte",
        model="B550M DS3H",
        price=1899.00,
        power_consumption=25,
        max_ram_capacity=128,
        max_ram_frequency=8000,
        ram_socket_type="DDR4",
        compatible_cpus=["5", "4", "3", "2", "T2", "A8", "A6", "T3"],
    ),
    Motherboard(
        maker="ASRock",
        model="B660M-HDV",
        price=1599.00,
        power_consumption=15,
        max_ram_capacity=64,
        max_ram_frequency=5200,
        ram_socket_type="DDR4",
        compatible_cpus=[14, 13, 12, "G7"],
    ),
    Motherboard(
        maker="Gigabyte",
        model="A520M-S2H",
        price=1399.00,
        power_consumption=15,
        max_ram_capacity=64,
        max_ram_frequency=4000,
        ram_socket_type="DDR4",
        compatible_cpus=["5", "4", "3", "2", "T2", "A8", "A6", "T3"],
    ),
    Motherboard(
        maker="Biostar",
        model="Micro ATX B450MX-S",
        price=1599.00,
        power_consumption=20,
        max_ram_capacity=128,
        max_ram_frequency=3600,
        ram_socket_type="DDR4",
        compatible_cpus=[14, 13, 12, "G7"],
    ),
    Motherboard(
        maker="Gigabyte",
        model="Micro-ATX H510M K",
        price=1399.00,
        power_consumption=18,
        max_ram_capacity=64,
        max_ram_frequency=4000,
        ram_socket_type="DDR4",
        compatible_cpus=["10", "11", "G6", "G5"],
    ),
    Motherboard(
        maker="ASRock",
        model="A520M PHANTOM",
        price=1349.00,
        power_consumption=25,
        max_ram_capacity=128,
        max_ram_frequency=4000,
        ram_socket_type="DDR4",
        compatible_cpus=["5", "4", "3", "2", "T2", "A8", "A6", "T3"],
    ),
    Motherboard(
        maker="Gigabyte",
        model="B450M K",
        price=1299.00,
        power_consumption=15,
        max_ram_capacity=64,
        max_ram_frequency=4000,
        ram_socket_type="DDR4",
        compatible_cpus=["5", "4", "3", "2", "T2", "A8", "A6", "T3"],
    ),
    Motherboard(
        maker="MSI",
        model="PRO H510M-B",
        price=999.00,
        power_consumption=15,
        max_ram_capacity=64,
        max_ram_frequency=4000,
        ram_socket_type="DDR4",
        compatible_cpus=["10", "11", "G6", "G5"],
    ),
    Motherboard(
        maker="ASUS",
        model="Pro A320M-R",
        price=849.00,
        power_consumption=15,
        max_ram_capacity=32,
        max_ram_frequency=4000,
        ram_socket_type="DDR4",
        compatible_cpus=["5", "4", "3", "2", "T2", "A8", "A6", "T3"],
    ),
    Motherboard(
        maker="Micro-ATX",
        model="PRIME A620M-K-CSM",
        price=1699.00,
        power_consumption=20,
        max_ram_capacity=96,
        max_ram_frequency=4000,
        ram_socket_type="DDR5",
        compatible_cpus=[7, 8],
    ),
    Motherboard(
        maker="MSI",
        model="Pro A620M-E ProSeries",
        price=1228.00,
        power_consumption=15,
        max_ram_capacity=64,
        max_ram_frequency=4000,
        ram_socket_type="DDR5",
        compatible_cpus=[7, 8],
    ),
    Motherboard(
        maker="Biostar",
        model="H310mhp",
        price=2430.00,
        power_consumption=15,
        max_ram_capacity=32,
        max_ram_frequency=4000,
        ram_socket_type="DDR4",
        compatible_cpus=["9"],
    ),
    Motherboard(
        maker="Gigabyte",
        model="B365m Aorus",
        price=4176.00,
        power_consumption=15,
        max_ram_capacity=64,
        max_ram_frequency=4000,
        ram_socket_type="DDR4",
        compatible_cpus=["9"],
    ),
    Motherboard(
        maker="MSI",
        model="H510m-b",
        price=1104.00,
        power_consumption=15,
        max_ram_capacity=64,
        max_ram_frequency=4000,
        ram_socket_type="DDR4",
        compatible_cpus=["10", "11", "G6", "G5"],
    ),
    Motherboard(
        maker="Intel",
        model="H81",
        price=1104.00,
        power_consumption=10,
        max_ram_capacity=16,
        max_ram_frequency=4000,
        ram_socket_type="DDR4",
        compatible_cpus=["9"],
    ),
]


"""
----------------------------------------------------------------------------------
"""


psus = [
    PSU(
        maker="Corsair",
        model="HX1000",
        capacity=1000,
        price=2249.99,
    ),
    PSU(
        maker="EVGA",
        model="SuperNOVA 1000 G6",
        capacity=1000,
        price=2329.99,
    ),
    PSU(
        maker="Seasonic",
        model="PRIME TX-1000",
        capacity=1000,
        price=2399.99,
    ),
    PSU(
        maker="Cooler Master",
        model="V1000 Platinum",
        capacity=1000,
        price=1899.99,
    ),
    PSU(
        maker="be quiet!",
        model="Dark Power Pro 12 1500W",
        capacity=1500,
        price=4599.99,
    ),
    PSU(
        maker="Thermaltake",
        model="Toughpower GF1 850W",
        capacity=850,
        price=1359.99,
    ),
    PSU(
        maker="Corsair",
        model="RM850x",
        capacity=850,
        price=2249.99,
    ),
    PSU(
        maker="NZXT",
        model="C850",
        capacity=850,
        price=1329.99,
    ),
    PSU(
        maker="EVGA",
        model="SuperNOVA 750 G5",
        capacity=750,
        price=1219.99,
    ),
    PSU(
        maker="Seasonic",
        model="FOCUS GX-750",
        capacity=750,
        price=1449.99,
    ),
    PSU(
        maker="MSI",
        model="MAG A550BN 80 PLUS Bronze",
        capacity=550,
        price=949,
    ),
    PSU(
        maker="Cooler Master",
        model="Masterwatt",
        capacity=650,
        price=1399.00,
    ),
    PSU(
        maker="Cooler Master",
        model="MWE Bronze",
        capacity=700,
        price=1_599.00,
    ),
    PSU(
        maker="GR Burst",
        model="GR450",
        capacity=450,
        price=683.00,
    ),
        PSU(
        maker="EVGA",
        model="500W 80+",
        capacity=500,
        price=899.00,
    ),
    PSU(
        maker="MSI",
        model="MAG A550BN",
        capacity=550,
        price=949.00,
    ),
    PSU(
        maker="Thermaltake",
        model="PS-SPD-0600NPCWUS-W",
        capacity=600,
        price=1099.00,
    ),
    PSU(
        maker="Cooler Master",
        model="Masterwatt 650W",
        capacity=650,
        price=1399.00,
    ),
    PSU(
        maker="Cooler Master",
        model="MWE BRONZE",
        capacity=700,
        price=1599.00,
    ),
    PSU(
        maker="ASUS",
        model="Prime AP-750G",
        capacity=750,
        price=1699.00,
    ),
    PSU(
        maker="Cooler Master",
        model="G800",
        capacity=800,
        price=1799.00,
    ),
    PSU(
        maker="Cooler Master",
        model="MWE GOLD",
        capacity=850,
        price=2199.00,
    ),
    PSU(
        maker="Corsair",
        model="RM1000e 80 PLUS Gold",
        capacity=1000,
        price=2999.00,
    ),
    PSU(
        maker="XPG",
        model="Cybercore",
        capacity=1300,
        price=3299.00,
    ),
    PSU(
        maker="EVGA",
        model="1600W SuperNova G+",
        capacity=1600,
        price=7999.00,
    ),
    PSU(
        maker="GR Burst",
        model="GR450",
        capacity=450,
        price=683.00,
    ),
    PSU(
        maker="EVGA",
        model="100-N1-0400-L1",
        capacity=400,
        price=599.00,
    ), 
]
